/* 
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ContextBrokerLibrary.Model
{
    /// <summary>
    /// Defines Options6
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Options6
    {
        /// <summary>
        /// Enum KeyValues for value: keyValues
        /// </summary>
        [EnumMember(Value = "keyValues")]
        KeyValues = 1,

        /// <summary>
        /// Enum Values for value: values
        /// </summary>
        [EnumMember(Value = "values")]
        Values = 2,

        /// <summary>
        /// Enum Unique for value: unique
        /// </summary>
        [EnumMember(Value = "unique")]
        Unique = 3
    }
}