/* 
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ContextBrokerLibrary.Model
{
    /// <summary>
    /// Defines Options10
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Options10
    {
        /// <summary>
        /// Enum Append for value: append
        /// </summary>
        [EnumMember(Value = "append")]
        Append = 1,

        /// <summary>
        /// Enum KeyValues for value: keyValues
        /// </summary>
        [EnumMember(Value = "keyValues")]
        KeyValues = 2
    }
}