/* 
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace ContextBrokerLibrary.Model
{
    /// <summary>
    /// UpdateOrAppendEntityAttributesRequest
    /// </summary>
    [DataContract]
    public partial class UpdateOrAppendEntityAttributesRequest : IEquatable<UpdateOrAppendEntityAttributesRequest>,
        IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateOrAppendEntityAttributesRequest" /> class.
        /// </summary>
        /// <param name="ambientNoise">ambientNoise (required).</param>
        public UpdateOrAppendEntityAttributesRequest(Object ambientNoise = default(Object))
        {
            // to ensure "ambientNoise" is required (not null)
            if (ambientNoise == null)
            {
                throw new InvalidDataException(
                    "ambientNoise is a required property for UpdateOrAppendEntityAttributesRequest and cannot be null");
            }
            else
            {
                this.AmbientNoise = ambientNoise;
            }
        }

        /// <summary>
        /// Gets or Sets AmbientNoise
        /// </summary>
        [DataMember(Name = "ambientNoise", EmitDefaultValue = false)]
        public Object AmbientNoise { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateOrAppendEntityAttributesRequest {\n");
            sb.Append("  AmbientNoise: ").Append(AmbientNoise).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateOrAppendEntityAttributesRequest);
        }

        /// <summary>
        /// Returns true if UpdateOrAppendEntityAttributesRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateOrAppendEntityAttributesRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateOrAppendEntityAttributesRequest input)
        {
            if (input == null)
                return false;

            return
            (
                this.AmbientNoise == input.AmbientNoise ||
                (this.AmbientNoise != null &&
                 this.AmbientNoise.Equals(input.AmbientNoise))
            );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AmbientNoise != null)
                    hashCode = hashCode * 59 + this.AmbientNoise.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(
            ValidationContext validationContext)
        {
            yield break;
        }
    }
}