# Builds and publishes a docker images of the water controller

name: Publish Docker Container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build and push Docker image to GitHub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: sirpumpkinhead/ba_struempf_watercontroller/water-controller
          tag_with_ref: true
      - name: Build and push Docker image to DockerHub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: konstantinstruempf/ba_struempf_watercontroller
          tag_with_ref: true
